import { Health } from './healthCarousel/form/model'

export const mockHealths: Health[] = [
  {
    _id: '1',
    name: 'Arev',
    location: '101',
    agression: 1,
    courage: 1,
    practicality: 1,
    empathy: 1,
    caution: 1,
    spirituality: 1,
    energy: 7,
    health: 8,
    terror: 0,
    food: 3,
    wealth: 2,
    reputation: 1,
    experience: 6,
    magic: 3,
  },
  {
    _id: '2',
    name: 'Gusano',
    location: '101',
    agression: 1,
    courage: 1,
    practicality: 1,
    empathy: 1,
    caution: 1,
    spirituality: 1,
    energy: 7,
    health: 8,
    terror: 0,
    food: 3,
    wealth: 2,
    reputation: 1,
    experience: 6,
    magic: 3,
  },
  {
    _id: '3',
    name: 'Beor',
    location: '',
  },
  {
    _id: '4',
    name: 'Ailei',
    location: '',
  },
]
